
services: 
  db: 
    image: postgres:13.21-alpine3.21
    container_name: nj-challenge-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nj-challenge
    ports: 
      - 5432:5432
volumes:
  db-data: 